### ISSUE TITLE
Turn this into a GitHub Action

### ISSUE THREAD

**Issue by DonaldTsang** [entozoon/readme-kanban-board#3]
Is it possible to make this easier to use by allowing every commit to re-render the Kanban?

**Comment by entozoon** [comment]
Interesting idea. It can't be built into this package, but you could implement it in your project with some clever package.json scripts, along the lines of
```json
"scripts": {
  "precommit": "readme-kanban-board",
  "commit": "git add --all; git commit -m \"commit command or whatever\"; git push"
}
```
Or better yet, a git hook command that might run `npx readme-kanban-board`. Have a look at the docs here https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Comment by DonaldTsang** [comment]
This does look pretty interesting. Will look to it (Git Hooks) in a moment.
